USE [WINE_OS]
GO

/****** Object:  Table [dbo].[Charge]    Script Date: 18.03.2017 15:58:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Charge](
	[ID] [int] NOT NULL,
	[Bezeichnung] [varchar](max) NOT NULL,
	[Weingut_ID] [int] NOT NULL,
 CONSTRAINT [PK_Charge] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Charge]  WITH CHECK ADD  CONSTRAINT [FK_Charge_Weingut] FOREIGN KEY([Weingut_ID])
REFERENCES [dbo].[Weingut] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Charge] CHECK CONSTRAINT [FK_Charge_Weingut]
GO


