USE [master]
GO

/****** Object:  Database [WineOS]    Script Date: 19.02.2017 19:29:20 ******/
CREATE DATABASE [WineOS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WineOS', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\WineOS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WineOS_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\WineOS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WineOS] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WineOS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WineOS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WineOS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WineOS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WineOS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WineOS] SET ARITHABORT OFF 
GO

ALTER DATABASE [WineOS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WineOS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WineOS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WineOS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WineOS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WineOS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WineOS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WineOS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WineOS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WineOS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WineOS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WineOS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WineOS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WineOS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WineOS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WineOS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WineOS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WineOS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WineOS] SET  MULTI_USER 
GO

ALTER DATABASE [WineOS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WineOS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WineOS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WineOS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WineOS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WineOS] SET  READ_WRITE 
GO


