USE [master]
GO

/****** Object:  Database [WINE_OS]    Script Date: 16.01.2017 21:27:30 ******/
CREATE DATABASE [WINE_OS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WINE_OS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.WINE_OS\MSSQL\DATA\WINE_OS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WINE_OS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.WINE_OS\MSSQL\DATA\WINE_OS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WINE_OS] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WINE_OS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WINE_OS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WINE_OS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WINE_OS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WINE_OS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WINE_OS] SET ARITHABORT OFF 
GO

ALTER DATABASE [WINE_OS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WINE_OS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WINE_OS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WINE_OS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WINE_OS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WINE_OS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WINE_OS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WINE_OS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WINE_OS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WINE_OS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WINE_OS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WINE_OS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WINE_OS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WINE_OS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WINE_OS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WINE_OS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WINE_OS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WINE_OS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WINE_OS] SET  MULTI_USER 
GO

ALTER DATABASE [WINE_OS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WINE_OS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WINE_OS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WINE_OS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WINE_OS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WINE_OS] SET  READ_WRITE 
GO


